name: Build repo
on:
  push:
    branches:
      - main
      - dkannan
  pull_request:
    branches:
      - main
  schedule: 
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python 3.9.20
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.20

      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          pip install -r requirements.txt
          echo "Python requirements installed"

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: |
          npm install --legacy-peer-deps
          echo "NPM requirements installed"

      - name: Run frontend tests
        working-directory: ./frontend
        run: |
          npm run build