name: Run Frontend Tests with Coverage

on:
  push:
    branches:
      - main
      - dkannan
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run tests with coverage
        working-directory: ./frontend
        run: |
          npm run test -- --coverage --verbose --ci --passWithNoTests -- test/Workouts.test.js test/App.test.js test/ContactUs.test.js test/Footer.test.js test/Header.test.js

      - name: Upload coverage to Codecov
        if: always()
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN || '' }}  # Store your Codecov token in GitHub secrets
        run: bash <(curl -s https://codecov.io/bash) -f frontend/coverage/**/lcov.info
